name = input()
price = int(input())
weight = int(input())
money = int(input())
print(f'{'Чек':=^35}')
print(f'{'Товар:': <18}{name: >17}')
print(f'{'Цена:': <18}', '{: >17}'.format(str(weight) + "кг * " + str(price) + 'руб/кг'), sep="")
print(f'{'Итого:': <18}', '{: >17}'.format(str(price * weight) + 'руб'), sep="")
print(f'{'Внесено:': <18}', '{: >17}'.format(str(money) + 'руб'), sep="")
print(f'{'Сдача:': <18}', '{: >17}'.format(str(money - price * weight) + 'руб'), sep="")
print('=' * 35)